### ISSUE TITLE
Progress Indicator Not Showing

### ISSUE THREAD

**Issue by eniserkaya** [fayaz07/progress_dialog#6] opened 2019-04-22 06:16 UTC
Hi,

When i use this dialog, there is no progress indicator. The screen only has text. Is there any idea about this issue?

**Comment by fayaz07** [comment] 2019-04-22 08:59
Hi, we are working on it and we will fix it soon

**Comment by PuneethRegonda** [comment] 2019-04-22 17:21
The issue is fixed in the latest update 1.0.8

**Comment by fayaz07** [comment] 2019-04-23 03:42
Thanks @PuneethRegonda

**Closed as completed by fayaz07** 2019-04-23 03:42 UTC
